export const allCategories = [
    "All",
    "Romance",
    "Thriller",
    "Mystery",
    "Science Fiction",
    "Music",
    "Gaming",
    "Live",
    "News",
    "Sports",
    "Learning",
    "Fashion & Beauty",
    "Comedy",
    "Movies",
    "TV Shows",
    "Documentary",
    "Animation",
    "Kids",
    "Travel",
    "Food",
    "Technology",
    "Entertainment",
    "Recently Uploaded",
    "Trending",
  ];